# Generated by Django 2.2.5 on 2019-12-28 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20, verbose_name='班级名')),
                ('classcourse', models.CharField(max_length=20, verbose_name='课程名')),
                ('classsubjecttime', models.CharField(max_length=20, verbose_name='课时')),
                ('classsubday', models.CharField(max_length=50, verbose_name='上课时间')),
                ('classteacher', models.CharField(max_length=20, verbose_name='教师')),
                ('classtime', models.CharField(max_length=50, verbose_name='上课时间段')),
            ],
            options={
                'verbose_name': '班级课程表',
                'verbose_name_plural': '班级课程表',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程类',
                'verbose_name_plural': '课程类',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='科目')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师')),
                ('teaching', models.IntegerField(choices=[(1, '是'), (2, '否')], default=2, verbose_name='是否排课')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Course', verbose_name='所属课程')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
            },
        ),
        migrations.CreateModel(
            name='CourseANDSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_time', models.SmallIntegerField(verbose_name='课时')),
                ('property_CS', models.IntegerField(verbose_name='课程顺序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Course', verbose_name='所属课程')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Subject', verbose_name='所属科目')),
            ],
            options={
                'verbose_name': '课程--学科表',
                'verbose_name_plural': '课程--学科表',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(through='course_app.CourseANDSubject', to='course_app.Subject', verbose_name='包含学科'),
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级')),
                ('join_time', models.DateField(default=django.utils.timezone.now, verbose_name='开学时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Course', verbose_name='所属类型')),
            ],
            options={
                'verbose_name': '班级表',
                'verbose_name_plural': '班级表',
            },
        ),
    ]
